comments = """
I want one!
I want to win!
This is so cool!
Sign me up!
Good luck everyone.
count me in!
I would love this
Please let me win!
hope I win
Yes please!
I've been waiting my entire life for this!
"""

tagged_comments = """
{} this was what I was talking about.
{} wow, this is amazing.
{} sign us up!
{} count us in.
{} this is so cool!
Can we get one for all of us? {}
I've always wanted something like this {}
Yes please! {}
{} we could use this for sure.
{} I want to win
{} what do you want to bet?
{} i can't believe this!
this can't be real {}
"""